---

- name: If CentOS7,Stopping the firewalld.service.
  systemd:
    name: firewalld
    state: stopped
    enabled: no
  when: ansible_os_family == 'RedHat' and ansible_distribution_version.split('.')[0] == '7'


#- name: Remove firewalld Installed Package.
#  yum:
#    name: firewalld
#    state: absent
#  when: ansible_os_family == 'RedHat' and ansible_distribution_version.split('.')[0] == '7'

- name: If CentOS7,Install iptables-services
  yum:
    name: iptables-services
    state: present
  when: ansible_os_family == 'RedHat' and ansible_distribution_version.split('.')[0] == '7'

- name: If CentOS6,Install iptables.
  yum:
    name: iptables
    state: present
  when: ansible_os_family == 'RedHat' and ansible_distribution_version.split('.')[0] == '6'

- name: If CentOS 6, start iptables.
  service:
    name: iptables
    state: started
    enabled: yes
  when: ansible_os_family == 'RedHat' and ansible_distribution_version.split('.')[0] == '6'

- name: If CentOS 7, start iptables.
  systemd:
    name: iptables
    state: started
    enabled: yes
  when: ansible_os_family == 'RedHat' and ansible_distribution_version.split('.')[0] == '7'

- name: Close the iptables rules.
  shell:
    iptables -F
  



