---

- name: Modify system open file counters.
  lineinfile:
    path: /etc/security/limits.conf
    line: "{{ item }}"
  with_items:
    - '* soft nproc 165535'
    - '* hard nproc 165535'
    - '* soft nofile 165535'
    - '* hard nofile 165535'

- name: Shutdown transparent hugepage.
  shell: echo never > /sys/kernel/mm/transparent_hugepage/enabled && echo never > /sys/kernel/mm/transparent_hugepage/defrag

- name: Ignore Warning tips.
  lineinfile:
    path: /etc/rc.local
    line: "{{ item }}"
  with_items:
    - 'echo never > /sys/kernel/mm/transparent_hugepage/enabled'
    - 'echo never > /sys/kernel/mm/transparent_hugepage/defrag'



