---


- name: "Include OS-Specific variables"
  include_vars: "{{ ansible_os_family}}.yml"



- name: "Install | Import install-from-source.yml file"
  include: "install_from_source.yml"
  when:
    -  zabbix_server_install_from_source


- name: "Configure the zabbbix server"
  include: "configure.yml"

